name: Build Android release

on:
  create:
    tags:
      - v*

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build Android Release
        run: |
          echo "${{ secrets.APP_KEYSTORE }}" > app.keystore.asc
          gpg -d --passphrase "${{ secrets.APP_KEYSTORE_PASSPHRASE }}" --batch app.keystore.asc > android/app/app.keystore
          cd android && ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.MYAPP_UPLOAD_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.PMYAPP_UPLOAD_STORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.PMYAPP_UPLOAD_STORE_PASSWORD }}'
      - name: Set tag on GITHUB_ENV
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create .env file
        run: echo "API_URL=${{ secrets.API_URL }}" >> .env
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: android/app/build/outputs/apk/release/app-release.apk
          asset_name: app-${{ env.RELEASE_VERSION }}.apk
          tag: ${{ github.ref }}
          overwrite: true
      - uses: EndBug/add-and-commit@v5
        with:
          add: 'CHANGELOG.md'
          branch: develop
          message: 'Update CHANGELOG.md file'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
